name: readit
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  logger: ^2.5.0
  image_cropper: ^8.0.2
  google_mlkit_text_recognition: ^0.14.0
  google_fonts: ^6.2.1
  http: ^1.2.2

  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.17.5
  flutter_svg: ^2.1.0
  flutter_launcher_icons: ^0.14.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"


